// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmt5zzhH-KZm3_g8hXu202OlsHYQis8eo',
    appId: '1:131071073084:android:ca23a75490d3fe63399c39',
    messagingSenderId: '131071073084',
    projectId: 'rummage-31244',
    storageBucket: 'rummage-31244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmY8StfVKGV1NolA9E247wZ8bvie1zwrI',
    appId: '1:131071073084:ios:6877543c4e277848399c39',
    messagingSenderId: '131071073084',
    projectId: 'rummage-31244',
    storageBucket: 'rummage-31244.firebasestorage.app',
    iosBundleId: 'com.RummageApp.Rummage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4COl4hbJ56IeOxT-YZQM_UmAk6S1yV0k',
    appId: '1:131071073084:web:190182f46d8c1c97399c39',
    messagingSenderId: '131071073084',
    projectId: 'rummage-31244',
    authDomain: 'rummage-31244.firebaseapp.com',
    storageBucket: 'rummage-31244.firebasestorage.app',
    measurementId: 'G-K1KKLDF32Y',
  );
}
